import { StylesProvider } from './styles-provider'

import './globals.css'
import Header from './header'

export const metadata = {
  title: 'Modern Next.js + React Native',
  description: 'Generated by create solito app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StylesProvider>
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              width: '48rem',
              margin: '0 auto',
            }}
          >
            <Header />
            {children}
          </div>
        </StylesProvider>
      </body>
    </html>
  )
}
